ENV['RCT_NEW_ARCH_ENABLED'] = '1'

source 'https://github.com/oititec/ios-artifactory.git'
source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RnSdkExample' do
  config = use_native_modules!

  pod 'OILiveness3D_FT', git: 'https://github.com/oititec/ios-liveness3d-ft.git', branch: 'feature/31194-framework-update'
  pod 'CertifaceSDK', git: 'https://github.com/oititec/ios-oiti-sdk.git', branch: 'chore/31194-facetec-update'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
    rn_abs = File.expand_path(config[:reactNativePath], Pod::Config.instance.installation_root)
    with_env = File.join(rn_abs, 'scripts/xcode/with-environment.sh')
    script_phases = File.join(rn_abs, 'scripts/react_native_pods_utils/script_phases.sh')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['REACT_NATIVE_PATH'] = rn_abs
      end
      target.build_phases.each do |phase|
        next unless phase.respond_to?(:shell_script)
        next if phase.shell_script.nil?
        script = phase.shell_script
        script = script.gsub(/export RCT_SCRIPT_RN_DIR=.*\n/, "export RCT_SCRIPT_RN_DIR=\"#{rn_abs}\"\n")
        script = script.gsub(
          'WITH_ENVIRONMENT="$RCT_SCRIPT_RN_DIR/scripts/xcode/with-environment.sh"',
          "WITH_ENVIRONMENT=\"#{with_env}\""
        )
        script = script.gsub(
          'SCRIPT_PHASES_SCRIPT="$RCT_SCRIPT_RN_DIR/scripts/react_native_pods_utils/script_phases.sh"',
          "SCRIPT_PHASES_SCRIPT=\"#{script_phases}\""
        )
        script = script.gsub(
          '/bin/sh -c "$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT"',
          '"$WITH_ENVIRONMENT" "$SCRIPT_PHASES_SCRIPT"'
        )
        phase.shell_script = script
      end
    end
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |native_target|
        native_target.build_configurations.each do |build_config|
          build_config.build_settings['REACT_NATIVE_PATH'] = rn_abs
        end
      end
    end
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      patched = content.gsub(
        /#elif defined\(__cpp_consteval\)\R#  define FMT_USE_CONSTEVAL 1/,
        "#elif defined(__cpp_consteval)\n#  define FMT_USE_CONSTEVAL 0"
      ).gsub(
        /#elif FMT_GCC_VERSION >= 1002 \|\| FMT_CLANG_VERSION >= 1101\R#  define FMT_USE_CONSTEVAL 1/,
        "#elif FMT_GCC_VERSION >= 1002 || FMT_CLANG_VERSION >= 1101\n#  define FMT_USE_CONSTEVAL 0"
      )
      if patched != content
        File.chmod(0644, fmt_base)
        File.write(fmt_base, patched)
      end
    end
    hermes_replace_script = File.expand_path(
      File.join(config[:reactNativePath], 'sdks', 'hermes-engine', 'utils', 'replace_hermes_version.js'),
      __dir__
    )
    if File.exist?(hermes_replace_script)
      script_content = File.read(hermes_replace_script)
      fixed_script_content = script_content.gsub(
        'execSync(`tar -xf ${tarballURLPath} -C ${finalLocation}`);',
        'execSync(`tar -xf "${tarballURLPath}" -C "${finalLocation}"`);'
      )
      if fixed_script_content != script_content
        File.chmod(0644, hermes_replace_script)
        File.write(hermes_replace_script, fixed_script_content)
      end
    end
  end
end
