import type { CertifaceTheme } from '@certiface/sdk';

export const customTheme: CertifaceTheme = {
  // O provider efetivo vem do parâmetro `provider` em `CertifaceSDK.startJourney`
  // ou `startSaasJourney` (FaceTec/Fortface via token SaaS).
  //
  // FaceTec nativo: `facetec.*` (+ instructions/permission/processing compartilhados).
  // iProov: `iproov.*` + instructions/permission/processing/result.
  // Fortface (SaaS): `fortface.*` + instructions/permission/processing/result.
  // `result.*` = iProov e Fortface. FaceTec usa `facetec.*` para a tela de resultado nativa.
  // Permission bottom sheet / openSettings / closeButton = iOS-only (todos os providers no Android).

  facetec: {
    colors: {
      readyScreenHeader: '#FFD166',
      readyScreenSubtext: '#9CA3AF',
      readyScreenOvalFill: '#FF6B35',
      readyScreenTextBackground: '#444444',
      resultScreenMessage: '#EEF6F8',
      resultScreenForeground: '#EEF6F8',
      resultScreenBackground: '#1A1A1A',
      resultScreenActivityIndicator: '#EEF6F8',
      resultScreenUploadProgressBarFill: '#EEF6F8',
      resultScreenUploadProgressFill: '#EEF6F8',
      resultScreenUploadProgressBarTrack: '#444444',
      resultScreenResultAnimationBackground: '#2E2E2E',
      resultScreenResultAnimationForeground: '#EEF6F8',
      ovalStroke: '#FF6B35',
      ovalProgressFirst: '#FF6B35',
      ovalProgressSecond: '#FFD700',
      overlayBackground: '#80000000',
      frameBorder: '#FF6B35',
      frameBackground: '#1A1A1A',
      feedbackBarBackground: '#FFF8DC',
      feedbackMessage: '#333333',
      guidanceBackground: '#2E2E2E',
      guidanceForeground: '#FACC15',
      retryScreenHeader: '#FF5252',
      retryScreenSubtext: '#DD3333',
      retryScreenOvalStroke: '#FFFFFF',
      retryScreenImageBorder: '#FFFFFF',
      guidanceButtonTextNormal: '#111827',
      guidanceButtonTextHighlight: '#111827',
      guidanceButtonTextDisabled: '#AAAAAA',
      guidanceButtonBackgroundNormal: '#FF6B35',
      guidanceButtonBackgroundHighlight: '#FF6B35',
      guidanceButtonBackgroundDisabled: '#666666',
      guidanceButtonBorder: '#FF6B35',
    },
    texts: {
      readyHeader1: 'Prepare-se',
      readyHeader2: 'para verificação',
      readyMessage1: 'Posicione seu rosto',
      readyMessage2: 'dentro do círculo',
      readyButton: 'Iniciar',
      retryHeader: 'Vamos tentar novamente',
      retrySubheader: 'Ajustes necessários',
      retryMessageSmile: 'Mantenha uma expressão neutra',
      retryMessageLighting: 'Procure um ambiente bem iluminado',
      retryMessageContrast: 'Evite fundos muito claros ou muito escuros',
      retryYourPicture: 'Sua foto',
      retryIdealPicture: 'Foto ideal',
      retryButton: 'Tentar Novamente',
      resultUploadMessage: 'Enviando validação',
      resultSuccessMessage: 'Verificação concluída!',
      processingMessage: 'Processando sua verificação facial...',
      feedbackLookStraightInOval: 'Olhe diretamente para a câmera',
      feedbackCenterFace: 'Centralize seu rosto',
      feedbackFaceNotFound: 'Rosto não encontrado',
      feedbackFaceNotLookingStraightAhead: 'Olhe para frente',
      feedbackFaceNotUpright: 'Mantenha o rosto alinhado',
      feedbackHoldSteady: 'Mantenha-se parado',
      feedbackMovePhoneAway: 'Afaste o dispositivo',
      feedbackMovePhoneCloser: 'Aproxime o dispositivo',
      feedbackMovePhoneToEyeLevel: 'Mova o dispositivo para a altura dos olhos',
      feedbackUseEvenLighting: 'Use iluminação uniforme',
      feedbackFrameYourFace: 'Enquadre seu rosto',
      feedbackHoldSteady1: 'Mantenha-se parado',
      feedbackHoldSteady2: 'Quase lá',
      feedbackHoldSteady3: 'Continue parado',
      feedbackRemoveDarkGlasses: 'Remova óculos escuros',
      feedbackNeutralExpression: 'Mantenha expressão neutra',
      feedbackConditionsTooBright: 'Ambiente muito claro',
      feedbackBrightenYourEnvironment: 'Melhore a iluminação do ambiente',
    },
    assets: {
      overlayBrandImage: 'people',
      cancelButtonIcon: 'cancel_button',
      resultScreenCustomActivityIndicatorImage:
        'animated_activity_indicator_offwhite',
      resultScreenCustomActivityIndicatorAnimation:
        'animated_activity_indicator_offwhite',
      resultScreenSuccessImage: 'success_icon',
      resultScreenErrorImage: 'error_icon',
      resultScreenSuccessBackgroundImage: 'people',
      resultScreenErrorBackgroundImage: 'env',
      resultScreenSuccessAnimation: 'animated_success_offwhite',
      resultScreenErrorAnimation: 'animated_unsuccess_offwhite',
    },
    fonts: {
      readyScreenHeader: 'sixty',
      readyScreenSubtext: 'sixty',
      resultScreenMessage: 'sixty',
      retryScreenHeader: 'sixty',
      retryScreenSubtext: 'sixty',
      feedbackMessage: 'sixty',
      guidanceHeader: 'sixty',
      guidanceSubtext: 'sixty',
      guidanceButton: 'sixty',
    },
    sizes: {
      guidanceButtonBorderWidth: 2,
      guidanceRetryScreenImageBorderWidth: 3,
      frameBorderWidth: 4,
      frameCornerRadius: 8,
      frameElevation: 5,
      feedbackElevation: 8,
      feedbackCornerRadius: 12,
      guidanceButtonCornerRadius: 12,
      guidanceRetryScreenImageCornerRadius: 12,
      readyScreenTextBackgroundCornerRadius: 12,
      ovalStrokeWidth: 4,
      ovalProgressStrokeWidth: 6,
      ovalProgressRadialOffset: 0,
      ovalProgressWidth: 6,
      ovalProgressOffset: 0,
      resultScreenAnimationRelativeScale: 1,
      resultScreenCustomActivityIndicatorRotationInterval: 1000,
    },
    flags: {
      overlayShowBrandingImage: false,
      feedbackEnablePulsatingText: true,
      resultScreenShowUploadProgressBar: true,
    },
    configuration: {
      cancelButtonLocation: 'TOP_LEFT',
      exitAnimationStyle: 'CIRCLE_FADE',
    },
  },

  iproov: {
    fontResource: 'sixty',
    fontPath: 'fonts/sixty.ttf',
    colors: {
      closeButtonColor: '#FFFFFF',
      title: '#F59E0B',
      titleBackground: '#2E2E2E',
      promptText: '#60A5FA',
      promptBackground: '#1A1A1A',
      background: '#FF6B35',
      ovalReady: '#FF6B35',
      ovalNotReady: '#FF3030',
      ovalCapturing: '#22D3EE',
      ovalCompleted: '#FF6B35',
    },
    texts: {
      title: 'Verificação Biométrica',
      processingMessage: 'Processando sua verificação facial...',
    },
    assets: {
      closeButtonIcon: 'fc_arrow_left',
      logoImage: 'people',
    },
    fonts: {
      instructionsTitleFont: 'sixty',
      instructionsCaptionFont: 'sixty',
      instructionsDocumentTypesInstructionsFont: 'sixty',
      instructionsDocumentTipsInstructionsFont: 'sixty',
      instructionsButtonFont: 'sixty',
      permissionTitleFont: 'sixty',
      permissionCaptionFont: 'sixty',
      permissionButtonFont: 'sixty',
      resultMessageFont: 'sixty',
      resultRetryButtonFont: 'sixty',
    },
    configuration: {
      timeoutSecs: 60,
      orientationGpa: 'PORTRAIT',
      orientationLa: 'PORTRAIT',
      filterStyle: 'natural',
      naturalStyle: 'clear',
    },
    flags: {
      isEnabledScreenShots: true,
      disableExteriorEffects: false,
      promptRoundedCorners: true,
    },
  },

  // Fortface — startSaasJourney (provider resolvido pelo token).
  fortface: {
    colors: {
      cameraBackground: '#0D47A1',
      cameraMessageText: '#FFFFFF',
      cameraNeutral: '#CDCDCD',
      cameraAlert: '#511f7d',
      cameraSuccess: '#5FC213',
      cameraBrightnessAlert: '#24B8C2',
      cameraLoading: '#5FC213',
      cameraLoadingStroke: '#FFFFFF',
      cameraIconBackground: '#F1F1F1',
      // Usado com screenMode: 'MODAL'.
      modalOverlay: '#80000000',
    },
    texts: {
      cameraStartMessage: 'Enquadre o rosto no oval',
      cameraFaceNoCenter: 'Centralize o rosto',
      cameraFacePositioned: 'Aguarde, não se mexa',
      cameraNoFace: 'Posicione o rosto aqui',
      cameraFaceFar: 'Aproxime o rosto',
      cameraFaceNear: 'Afaste o rosto',
      cameraFaceCenterLeft: 'Mova à esquerda',
      cameraFaceCenterRight: 'Mova à direita',
      cameraFaceCenterUp: 'Mova para cima',
      cameraFaceCenterDown: 'Mova para baixo',
      cameraFacePitchUp: 'Abaixe o rosto',
      cameraFacePitchDown: 'Levante o rosto',
      cameraNoFaceYaw: 'Olhe para frente',
      cameraNoFaceRoll: 'Cabeça reta',
      cameraFaceRollLeft: 'Incline à esquerda',
      cameraFaceRollRight: 'Incline à direita',
      cameraFaceBrightnessLow: 'Melhore a luz',
      cameraFaceBrightnessHigh: 'Diminua a luz',
      processingMessage: 'Processando sua verificação facial...',
    },
    assets: {
      cancelButtonIcon: 'fortface_cancel_button_light',
      cameraLogo: 'people',
      brightnessHighIcon: 'ic_brightness_high',
      brightnessLowIcon: 'ic_brightness_low',
    },
    fonts: {
      cameraMessage: 'sixty',
      cameraFooter: 'sixty',
    },
    sizes: {
      cameraTimeout: 30,
      cameraMinStabilizationTime: 2,
      cameraMaxStabilizationTime: 3,
      brightnessValidationTimeout: 10,
      // Usado com screenMode: 'MODAL' (0–1).
      modalOverlayOpacity: 0.6,
    },
    flags: {
      cancelButtonEnable: true,
      cameraFrameTextVisible: true,
    },
    configuration: {
      cancelPosition: 'LEFT',
      // Default do exemplo: FULL_SCREEN. Para overlay: screenMode: 'MODAL' + colors.modalOverlay + sizes.modalOverlayOpacity.
      screenMode: 'FULL_SCREEN',
      screenOrientation: 'AUTOMATIC',
      // Arquivo JSON de customização Fortface no assets do app (quando aplicável).
      // customizationJsonFileName: 'fortface_customization.json',
    },
  },

  instructions: {
    configuration: {
      showInstructionScreen: true,
    },
    flags: {
      statusBarIsDarkIcons: false,
    },
    colors: {
      statusBar: '#9bd4ce',
      background: '#9bd4ce',
      backButtonIcon: '#00A89C',
      backButtonColor: '#00A89C',
      bottomSheet: '#FFFFFF',
      title: '#00A89C',
      caption: '#6B7280',
      firstInstructionTitle: '#374151',
      secondInstructionTitle: '#374151',
      firstInstructionIconBackground: '#00A89C',
      firstInstructionIconBorder: '#00A89C',
      secondInstructionIconBackground: '#00A89C',
      secondInstructionIconBorder: '#00A89C',
      continueButtonText: '#FFFFFF',
      continueButtonTextColor: '#FFFFFF',
      continueButtonBackground: '#00A89C',
      continueButtonBorder: '#00A89C',
    },
    texts: {
      title: 'Verificação de Identidade',
      caption: 'Siga as instruções para completar o processo',
      firstInstruction: 'Escolha um ambiente bem iluminado',
      secondInstruction: 'Não use bonés, máscaras ou óculos escuros',
      continueButton: 'Continuar',
    },
    assets: {
      backButtonIcon: 'fc_arrow_left',
      contextImage: 'woman_liveness_example',
      contextImageScale: 'fillBounds',
      contextImageHeightFraction: 1,
      firstInstructionIcon: 'lamp_example',
      secondInstructionIcon: 'face',
      instructionIconScale: 'fillBounds',
      instructionIconSize: 60,
    },
    fonts: {
      title: 'sixty',
      caption: 'sixty',
      firstInstructionTitle: 'sixty',
      secondInstructionTitle: 'sixty',
      continueButton: 'sixty',
    },
    sizes: {
      bottomSheetCornerRadius: 16,
      titleFontSize: 20,
      captionFontSize: 16,
      firstInstructionTitleFontSize: 14,
      secondInstructionTitleFontSize: 14,
      continueButtonFontSize: 16,
    },
  },

  // Bottom sheet / openSettings / closeButton: iOS-only. No Android a tela de permissão é simplificada.
  permission: {
    flags: {
      statusBarIsDarkIcons: false,
    },
    colors: {
      statusBar: '#9bd4ce',
      background: '#9bd4ce',
      backButtonIcon: '#374151',
      backButtonBackground: '#FFFFFF',
      backButtonBorder: '#00A89C',
      cameraImage: '#00A89C',
      title: '#00A89C',
      caption: '#6B7280',
      checkPermissionButtonText: '#FFFFFF',
      checkPermissionButtonBackground: '#00A89C',
      checkPermissionButtonBorder: '#00A89C',
      bottomSheet: '#FFFFFF',
      bottomSheetTitle: '#00A89C',
      bottomSheetCaption: '#6B7280',
      openSettingsButtonText: '#FFFFFF',
      openSettingsButtonBackground: '#00A89C',
      openSettingsButtonBorder: '#00A89C',
      closeButtonText: '#00A89C',
      closeButtonBackground: '#FFFFFF',
      closeButtonBorder: '#00A89C',
    },
    texts: {
      title: 'Permissões Necessárias',
      caption: 'Precisamos acessar sua câmera para a verificação biométrica',
      checkPermissionButton: 'Permitir Acesso',
      bottomSheetTitle: 'Acesso à câmera negado',
      bottomSheetCaption:
        'Abra as configurações do dispositivo e permita o uso da câmera',
      openSettingsButton: 'Abrir Configurações',
      closeButton: 'Fechar',
    },
    assets: {
      backButtonIcon: 'close_icon',
      cameraImage: 'camera_permission',
    },
    fonts: {
      title: 'sixty',
      caption: 'sixty',
      checkPermissionButton: 'sixty',
      bottomSheetTitle: 'sixty',
      bottomSheetCaption: 'sixty',
      openSettingsButton: 'sixty',
      closeButton: 'sixty',
    },
    sizes: {
      // FontSize e bottom sheet: iOS-only em todos os providers no Android.
      titleFontSize: 20,
      captionFontSize: 16,
      checkPermissionButtonFontSize: 16,
      bottomSheetTitleFontSize: 20,
      bottomSheetCaptionFontSize: 16,
      openSettingsButtonFontSize: 16,
      closeButtonFontSize: 16,
    },
  },

  processing: {
    flags: {
      statusBarIsDarkIcons: true,
    },
    colors: {
      statusBar: '#1A1A1A',
      background: '#1A1A1A',
      loading: '#FFFFFF',
    },
    texts: {
      message: 'Processando sua verificação facial...',
    },
    sizes: {
      loadingIndicatorSize: 100,
      loadingIndicatorWidth: 10,
      spinnerSize: 5,
      spinnerWidth: 2,
    },
    fonts: {
      message: 'sixty',
    },
  },

  // iProov + Fortface. FaceTec usa facetec.texts/colors/fonts de resultado.
  result: {
    colors: {
      successStatusBar: '#E8F5E8',
      successBackground: '#E8F5E8',
      successText: '#2E7D32',
      errorStatusBar: '#1f7365',
      errorBackground: '#1f7365',
      errorText: '#423c3c',
      retryBackground: '#dbabab',
      retryText: '#1f7365',
      retryButtonText: '#FF6B35',
      retryButtonBackground: '#FFFFFF',
      retryButtonBorder: '#FFFFFF',
    },
    texts: {
      success: 'Verificação concluída com sucesso!',
      error: 'Houve um erro na verificação. Tente novamente.',
      retryButton: 'Tentar Novamente',
    },
    assets: {
      successImage: 'success_icon',
      errorImage: 'error_icon',
      retryImage: 'return_button',
    },
    fonts: {
      text: 'sixty',
      retryButton: 'sixty',
    },
    flags: {
      successStatusBarIsDarkIcons: true,
      errorStatusBarIsDarkIcons: true,
    },
    sizes: {
      textFontSize: 20,
      retryButtonFontSize: 16,
    },
  },
};
