import type { CertifaceTheme } from '@certiface/sdk';

export const customTheme: CertifaceTheme = {
  facetec: {
    colors: {
      readyScreenHeader: '#FFD166',
      readyScreenSubtext: '#9CA3AF',
      readyScreenOvalFill: '#FF6B35',
      readyScreenTextBackground: '#444444',
      resultScreenForeground: '#FF6B35',
      resultScreenBackground: '#F0F8FF',
      ovalStroke: '#FF6B35',
      ovalProgressFirst: '#FF6B35',
      ovalProgressSecond: '#FFD700',
      overlayBackground: '#80000000',
      frameBorder: '#FF6B35',
      frameBackground: '#1A1A1A',
      feedbackBarBackground: '#FFF8DC',
      feedbackMessage: '#333333',
      guidanceBackground: '#2E2E2E',
      guidanceForeground: '#FACC15',
      guidanceButtonTextNormal: '#111827',
      guidanceButtonTextHighlight: '#111827',
      guidanceButtonTextDisabled: '#AAAAAA',
      guidanceButtonBackgroundNormal: '#FF6B35',
      guidanceButtonBackgroundHighlight: '#FF6B35',
      guidanceButtonBackgroundDisabled: '#666666',
      guidanceButtonBorder: '#FF6B35',
    },
    texts: {
      readyHeader1: 'Prepare-se',
      readyHeader2: 'para verificação',
      readyMessage1: 'Posicione seu rosto',
      readyMessage2: 'dentro do círculo',
      readyButton: 'Iniciar',
      retryHeader: 'Vamos tentar novamente',
      retrySubheader: 'Ajustes necessários',
      retryButton: 'Tentar Novamente',
      resultSuccessMessage: 'Verificação concluída!',
      feedbackCenterFace: 'Centralize seu rosto',
      feedbackHoldSteady: 'Mantenha-se parado',
      feedbackMovePhoneCloser: 'Aproxime o dispositivo',
      feedbackMovePhoneAway: 'Afaste o dispositivo',
    },
    assets: {
      overlayBrandImage: 'shell',
      cancelButtonIcon: 'shell',
      resultScreenCustomActivityIndicatorImage: 'shell',
    },
    fonts: {
      readyScreenHeader: 'sixty',
      readyScreenSubtext: 'sixty',
      resultScreenMessage: 'sixty',
      retryScreenHeader: 'sixty',
      retryScreenSubtext: 'sixty',
      feedbackMessage: 'sixty',
      guidanceHeader: 'sixty',
      guidanceSubtext: 'sixty',
      guidanceButton: 'sixty',
    },
    sizes: {
      guidanceButtonBorderWidth: 2,
      frameBorderWidth: 2,
      frameCornerRadius: 8,
      frameElevation: 5,
      feedbackElevation: 8,
      feedbackCornerRadius: 12,
      guidanceButtonCornerRadius: 12,
      guidanceRetryScreenImageBorderWidth: 3,
      guidanceRetryScreenImageCornerRadius: 12,
    },
    flags: {
      overlayShowBrandingImage: true,
      feedbackEnablePulsatingText: true,
    },
  },
  iproov: {
    fontResource: 'sixty',
    fontPath: 'fonts/sixty.ttf',
    colors: {
      closeButtonColor: '#22D3EE',
      title: '#F59E0B',
      titleBackground: '#2E2E2E',
      promptText: '#60A5FA',
      promptBackground: '#1A1A1A',
      background: '#FF6B35',
      ovalReady: '#FF6B35',
      ovalNotReady: '#FF3030',
      ovalCapturing: '#22D3EE',
      ovalCompleted: '#FF6B35',
    },
    texts: {
      title: 'Verificação Biométrica',
    },
    assets: {
      logoImage: 'shell',
    },
    fonts: {
      instructionsTitleFont: 'sixty',
      instructionsCaptionFont: 'sixty',
      instructionsDocumentTypesInstructionsFont: 'sixty',
      instructionsDocumentTipsInstructionsFont: 'sixty',
      instructionsButtonFont: 'sixty',
      permissionTitleFont: 'sixty',
      permissionCaptionFont: 'sixty',
      permissionButtonFont: 'sixty',
      resultMessageFont: 'sixty',
      resultRetryButtonFont: 'sixty',
    },
  },
  instructions: {
    configuration: {
      showInstructionScreen: true,
    },
    flags: {
      statusBarIsDarkIcons: false,
    },
    colors: {
      statusBar: '#2E2E2E',
      background: '#2E2E2E',
      backButtonBackground: '#2E2E2E',
      backButtonBorder: '#2E2E2E',
      bottomSheet: '#1A1A1A',
      title: '#F59E0B',
      caption: '#38BDF8',
      firstInstructionTitle: '#A78BFA',
      secondInstructionTitle: '#34D399',
      continueButtonText: '#111827',
      continueButtonTextColor: '#111827',
      continueButtonBackground: '#FF6B35',
      continueButtonBorder: '#FF6B35',
    },
    texts: {
      title: 'Verificação de Identidade',
      caption: 'Siga as instruções para completar o processo',
      firstInstruction: 'Mantenha o documento bem iluminado',
      secondInstruction: 'Use um documento oficial com foto',
      continueButton: 'Continuar',
    },
    assets: {
      backButtonIcon: 'shell',
      contextImage: 'shell',
      firstInstructionIcon: 'shell',
      secondInstructionIcon: 'shell',
    },
    fonts: {
      title: 'sixty',
      caption: 'sixty',
      firstInstructionTitle: 'sixty',
      secondInstructionTitle: 'sixty',
      continueButton: 'sixty',
    },
  },
  permission: {
    colors: {
      statusBar: '#2E2E2E',
      background: '#2E2E2E',
      backButtonIcon: '#2E2E2E',
      backButtonBackground: '#2E2E2E',
      backButtonBorder: '#2E2E2E',
      cameraImage: '#F59E0B',
      title: '#F59E0B',
      caption: '#38BDF8',
      checkPermissionButtonText: '#111827',
      checkPermissionButtonBackground: '#FF6B35',
      checkPermissionButtonBorder: '#FF6B35',
      bottomSheet: '#FF6B35',
      bottomSheetTitle: '#FF6B35',
      bottomSheetCaption: '#FF6B35',
      openSettingsButtonText: '#FF6B35',
      openSettingsButtonBackground: '#FF6B35',
      openSettingsButtonBorder: '#FF6B35',
      closeButtonText: '#FF6B35',
      closeButtonBackground: '#FF6B35',
      closeButtonBorder: '#FF6B35',
    },
    texts: {
      title: 'Permissões Necessárias',
      caption: 'Permissões Necessárias',
      checkPermissionButton: 'Permitir Acesso',
      bottomSheetTitle: 'Permitir Acesso',
      bottomSheetCaption: 'Permitir Acesso',
      openSettingsButton: 'Permitir Acesso',
      closeButton: 'Permitir Acesso',
    },
    assets: {
      backButtonIcon: 'shell',
      cameraImage: 'shell',
    },
    fonts: {
      title: 'sixty',
      caption: 'sixty',
      checkPermissionButton: 'sixty',
      bottomSheetTitle: 'sixty',
      bottomSheetCaption: 'sixty',
      openSettingsButton: 'sixty',
      closeButton: 'sixty',
    },
  },
  processing: {
    colors: {
      statusBar: '#1A1A1A',
      background: '#1A1A1A',
      loading: '#FFFFFF',
    },
  },
  result: {
    colors: {
      successStatusBar: '#E8F5E8',
      successBackground: '#E8F5E8',
      successText: '#2E7D32',
      errorStatusBar: '#FFEBEE',
      errorBackground: '#FFEBEE',
      errorText: '#C62828',
      retryBackground: '#C62828',
      retryText: '#FFEBEE',
      retryButtonText: '#FF6B35',
      retryButtonBackground: '#FFFFFF',
      retryButtonBorder: '#FFFFFF',
    },
    texts: {
      success: 'Verificação concluída com sucesso!',
      error: 'Houve um erro na verificação. Tente novamente.',
      retryButton: 'Tentar Novamente',
    },
    assets: {
      successImage: 'shell',
      errorImage: 'shell',
      retryImage: 'shell',
    },
    fonts: {
      text: 'sixty',
      retryButton: 'sixty',
    },
  },
};
